* a) Warum brauchen wir ein ``try-catch`` in der ``Main`` Methode um ``kunde.ValidateKunde();`` sowie miteinander vergleichen zu können ``kunde.ValidateKundeGuardClause();``?
> Ansonsten würde die geworfene ``Exception`` nicht gefangen werden und zu einem Programmabsturz führen. Wir könnten somit nicht

* b) Die gültigen Zustände des Programms sind mit ✅ gekennzeichnet. Können diese zu einem gültigen Zustand ✅ Zusammengefasst werden? 
